// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtMXfpXEGSEfRY84qo2sicOagAymhZMsw',
    appId: '1:587220375167:web:99a05e61b0e913f3dfd14a',
    messagingSenderId: '587220375167',
    projectId: 'app-newsverses',
    authDomain: 'app-newsverses.firebaseapp.com',
    storageBucket: 'app-newsverses.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxu3_TRXx4_8ZStEVwNIxZwNzvltmaz1A',
    appId: '1:587220375167:android:9cfc778ac5763de8dfd14a',
    messagingSenderId: '587220375167',
    projectId: 'app-newsverses',
    storageBucket: 'app-newsverses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiW-8pksBy8LBmEvyHSUxDQ85roDjarc',
    appId: '1:587220375167:ios:d24f7a72b6f534cfdfd14a',
    messagingSenderId: '587220375167',
    projectId: 'app-newsverses',
    storageBucket: 'app-newsverses.firebasestorage.app',
    iosBundleId: 'com.example.newsverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiW-8pksBy8LBmEvyHSUxDQ85roDjarc',
    appId: '1:587220375167:ios:d24f7a72b6f534cfdfd14a',
    messagingSenderId: '587220375167',
    projectId: 'app-newsverses',
    storageBucket: 'app-newsverses.firebasestorage.app',
    iosBundleId: 'com.example.newsverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtMXfpXEGSEfRY84qo2sicOagAymhZMsw',
    appId: '1:587220375167:web:f14231aa512ab676dfd14a',
    messagingSenderId: '587220375167',
    projectId: 'app-newsverses',
    authDomain: 'app-newsverses.firebaseapp.com',
    storageBucket: 'app-newsverses.firebasestorage.app',
  );
}
